trigger:
- "*"

variables:
  javaVersion: '17'
  mavenArtifactName: 'mottu-control-*.jar'
  imageRepository: 'mottu-control'
  dnsLabelApp: 'app-mottu-fiap-557047'
  dnsLabelDb: 'db-mottu-fiap-557047'
  resourceGroup: 'rg-mottu-fiap'
  location: 'brazilsouth'
  postgresContainerName: 'postgres-db'
  postgresDb: '$(POSTGRES_DB)'
  postgresUser: '$(POSTGRES_USER)'
  appContainerName: 'mottu-app'
  dockerRegistryName: 'acrmottuRM557047'
  dockerRegistryUsername: '$(DOCKER_REGISTRY_USERNAME)'
  dockerRegistryPassword: '$(DOCKER_REGISTRY_PASSWORD)'

stages:
- stage: Build
  displayName: 'CI - Build & Docker'
  jobs:
  - job: BuildAndDocker
    displayName: 'Build JAR and Docker Image'
    pool:
      vmImage: 'ubuntu-latest'
    
    steps:
    - task: JavaToolInstaller@0
      inputs:
        versionSpec: $(javaVersion)
        jdkArchitectureOption: 'x64'
        jdkSourceOption: 'PreInstalled'

    - task: Maven@4
      displayName: 'Maven Package (Skip Tests)'
      inputs:
        mavenPomFile: '$(Build.SourcesDirectory)/sprint4-devops/pom.xml'
        goals: 'package'
        options: '-DskipTests'
        publishJUnitTestResults: false

    - task: Docker@2
      displayName: 'Login to ACR'
      inputs:
        command: 'login'
        containerRegistry: 'AcrConnection'

    - task: Docker@2
      displayName: 'Build Docker Image'
      inputs:
        command: build
        dockerfile: '$(Build.SourcesDirectory)/sprint4-devops/Dockerfile'
        buildContext: '$(Build.SourcesDirectory)/sprint4-devops'
        tags: |
          $(Build.BuildId)

    - task: Docker@2
      displayName: 'Push Image to ACR'
      inputs:
        command: 'push'
        repository: $(imageRepository)
        containerRegistry: 'AcrConnection'
        tags: |
          $(Build.BuildId)
          latest

- stage: Deploy
  displayName: 'CD - Deploy to Azure'
  dependsOn: Build
  condition: succeeded()
  
  jobs:
  - job: DeployToACI
    displayName: 'Deploy to ACI'
    pool:
      vmImage: 'ubuntu-latest'
      
    steps:
    - task: AzureCLI@2
      displayName: 'Deploy PostgreSQL & App'
      inputs:
        azureSubscription: 'AzureSubscriptionConnection'
        scriptType: 'pscore'
        scriptLocation: 'inlineScript'
        inlineScript: |
          # Deploy do PostgreSQL
          az container create `
            --resource-group $(resourceGroup) `
            --name $(postgresContainerName) `
            --image postgres:15 `
            --os-type Linux `
            --ports 5432 `
            --cpu 1 `
            --memory 1.5 `
            --environment-variables "POSTGRES_DB=$(postgresDb)" "POSTGRES_USER=$(postgresUser)" "POSTGRES_PASSWORD=$(POSTGRES_PASSWORD)" `
            --dns-name-label $(dnsLabelDb) `
            --location $(location)

          Start-Sleep -Seconds 60

          $POSTGRES_IP = $(az container show --resource-group $(resourceGroup) --name $(postgresContainerName) --query ipAddress.ip --output tsv)
          $ACR_LOGIN_SERVER = $(az acr show --name $(dockerRegistryName) --query loginServer -o tsv)

          # Deploy da aplicação Java
          az container create `
            --resource-group $(resourceGroup) `
            --name $(appContainerName) `
            --image "$ACR_LOGIN_SERVER/$(imageRepository):$(Build.BuildId)" `
            --os-type Linux `
            --ports 8080 `
            --cpu 1 `
            --memory 1.5 `
            --registry-login-server $ACR_LOGIN_SERVER `
            --registry-username $(dockerRegistryUsername) `
            --registry-password $(dockerRegistryPassword) `
            --environment-variables "DB_URL=jdbc:postgresql://$POSTGRES_IP:5432/$(postgresDb)" "DB_USER=$(postgresUser)" "DB_PASSWORD=$(POSTGRES_PASSWORD)" `
            --dns-name-label $(dnsLabelApp) `
            --location $(location)
