# Configuração do Servidor
server.port=8080

# Configuração do Banco de Dados (agora PostgreSQL)
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

# Configuração do JPA/Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true

# Configuração de Segurança Estática para Testes (Basic Auth)
spring.security.user.name=mottu
spring.security.user.password=mottu123